//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiretorSkinner.Grafo.Seymour {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Seymour.IDiretorSkinnerGrafo")]
    public interface IDiretorSkinnerGrafo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarConceitos", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarConceitosResponse")]
        DiretorSkinner.Grafo.Tranporte.ConceitoDto[] ListarConceitos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarConceitos", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarConceitosResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ConceitoDto[]> ListarConceitosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarConceitoResponse")]
        DiretorSkinner.Grafo.Tranporte.ConceitoDto ListarConceito(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ConceitoDto> ListarConceitoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarConceitoResponse")]
        void SalvarConceito(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarConceitoResponse")]
        System.Threading.Tasks.Task SalvarConceitoAsync(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarConceitoResponse")]
        void DeletarConceito(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarConceitoResponse")]
        System.Threading.Tasks.Task DeletarConceitoAsync(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarDisciplinas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarDisciplinasResponse")]
        DiretorSkinner.Grafo.Tranporte.DisciplinaDto[] ListarDisciplinas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarDisciplinas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarDisciplinasResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.DisciplinaDto[]> ListarDisciplinasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarDisciplinaPorTipo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarDisciplinaPorTipoResponse")]
        DiretorSkinner.Grafo.Tranporte.DisciplinaDto[] ListarDisciplinaPorTipo(DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto tipoDisciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarDisciplinaPorTipo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarDisciplinaPorTipoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.DisciplinaDto[]> ListarDisciplinaPorTipoAsync(DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto tipoDisciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarDisciplinaResponse")]
        DiretorSkinner.Grafo.Tranporte.DisciplinaDto ListarDisciplina(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.DisciplinaDto> ListarDisciplinaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarDisciplinaResponse")]
        void SalvarDisciplina(DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarDisciplinaResponse")]
        System.Threading.Tasks.Task SalvarDisciplinaAsync(DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarDisciplinaResponse")]
        void DeletarDisciplina(DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarDisciplinaResponse")]
        System.Threading.Tasks.Task DeletarDisciplinaAsync(DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoasResponse")]
        DiretorSkinner.Grafo.Tranporte.PessoaDto[] ListarPessoas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoasResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaDto[]> ListarPessoasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoasPesquisa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoasPesquisaResponse")]
        DiretorSkinner.Grafo.Tranporte.PessoaDto[] ListarPessoasPesquisa(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoasPesquisa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoasPesquisaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaDto[]> ListarPessoasPesquisaAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorTipo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorTipoResponse")]
        DiretorSkinner.Grafo.Tranporte.PessoaDto[] ListarPessoaPorTipo(DiretorSkinner.Grafo.Tranporte.TipoPessoaDto tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorTipo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorTipoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaDto[]> ListarPessoaPorTipoAsync(DiretorSkinner.Grafo.Tranporte.TipoPessoaDto tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaResponse")]
        DiretorSkinner.Grafo.Tranporte.PessoaDto ListarPessoa(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaDto> ListarPessoaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorApelido", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorApelidoResponse")]
        DiretorSkinner.Grafo.Tranporte.PessoaDto ListarPessoaPorApelido(string apelido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorApelido", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorApelidoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaDto> ListarPessoaPorApelidoAsync(string apelido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorCodigo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorCodigoResponse")]
        DiretorSkinner.Grafo.Tranporte.PessoaDto ListarPessoaPorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorCodigo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorCodigoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaDto> ListarPessoaPorCodigoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarPessoaResponse")]
        void SalvarPessoa(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarPessoaResponse")]
        System.Threading.Tasks.Task SalvarPessoaAsync(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarPessoaResponse")]
        void DeletarPessoa(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarPessoaResponse")]
        System.Threading.Tasks.Task DeletarPessoaAsync(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorTodosConceitos", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorTodosConceitosRespo" +
            "nse")]
        DiretorSkinner.Grafo.Tranporte.PessoaPorConceitoDto[] ListarPessoaPorTodosConceitos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorTodosConceitos", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorTodosConceitosRespo" +
            "nse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaPorConceitoDto[]> ListarPessoaPorTodosConceitosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorConceitoResponse")]
        DiretorSkinner.Grafo.Tranporte.PessoaPorConceitoDto[] ListarPessoaPorConceito(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarPessoaPorConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaPorConceitoDto[]> ListarPessoaPorConceitoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaInserirConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaInserirConceitoResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaInserirConceito(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaInserirConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaInserirConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaInserirConceitoAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaAlterarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaAlterarConceitoResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaAlterarConceito(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaAlterarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaAlterarConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaAlterarConceitoAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaExcluirConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaExcluirConceitoResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaExcluirConceito(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaExcluirConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaExcluirConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaExcluirConceitoAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaSelecionarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaSelecionarConceitoResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaSelecionarConceito(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaSelecionarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaSelecionarConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaSelecionarConceitoAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaRelatorioConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaRelatorioConceitoResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaRelatorioConceito(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaRelatorioConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaRelatorioConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaRelatorioConceitoAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaInserirDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaInserirDisciplinaResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaInserirDisciplina(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaInserirDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaInserirDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaInserirDisciplinaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaAlterarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaAlterarDisciplinaResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaAlterarDisciplina(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaAlterarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaAlterarDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaAlterarDisciplinaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaExcluirDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaExcluirDisciplinaResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaExcluirDisciplina(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaExcluirDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaExcluirDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaExcluirDisciplinaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaSelecionarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaSelecionarDisciplinaResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaSelecionarDisciplina(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaSelecionarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaSelecionarDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaSelecionarDisciplinaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaRelatorioDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaRelatorioDisciplinaResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaRelatorioDisciplina(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaRelatorioDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaRelatorioDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaRelatorioDisciplinaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaInserirSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaInserirSalaDeAulaResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaInserirSalaDeAula(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaInserirSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaInserirSalaDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaInserirSalaDeAulaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaAlterarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaAlterarSalaDeAulaResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaAlterarSalaDeAula(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaAlterarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaAlterarSalaDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaAlterarSalaDeAulaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaExcluirSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaExcluirSalaDeAulaResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaExcluirSalaDeAula(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaExcluirSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaExcluirSalaDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaExcluirSalaDeAulaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaSelecionarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaSelecionarSalaDeAulaResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaSelecionarSalaDeAula(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaSelecionarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaSelecionarSalaDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaSelecionarSalaDeAulaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaRelatorioSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaRelatorioSalaDeAulaResponse")]
        DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaRelatorioSalaDeAula(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaRelatorioSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/CargaRelatorioSalaDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaRelatorioSalaDeAulaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarQtdePessoaPorTodasDisciplina" +
            "s", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarQtdePessoaPorTodasDisciplina" +
            "sResponse")]
        DiretorSkinner.Grafo.Tranporte.QtdePessoaPorDisciplinaDto[] ListarQtdePessoaPorTodasDisciplinas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarQtdePessoaPorTodasDisciplina" +
            "s", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarQtdePessoaPorTodasDisciplina" +
            "sResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.QtdePessoaPorDisciplinaDto[]> ListarQtdePessoaPorTodasDisciplinasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarQtdePessoaPorDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarQtdePessoaPorDisciplinaRespo" +
            "nse")]
        DiretorSkinner.Grafo.Tranporte.QtdePessoaPorDisciplinaDto[] ListarQtdePessoaPorDisciplina(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarQtdePessoaPorDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarQtdePessoaPorDisciplinaRespo" +
            "nse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.QtdePessoaPorDisciplinaDto[]> ListarQtdePessoaPorDisciplinaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarRepetenciaPorTodosTipos", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarRepetenciaPorTodosTiposRespo" +
            "nse")]
        DiretorSkinner.Grafo.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[] ListarRepetenciaPorTodosTipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarRepetenciaPorTodosTipos", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarRepetenciaPorTodosTiposRespo" +
            "nse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[]> ListarRepetenciaPorTodosTiposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarRepetenciaPorTipo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarRepetenciaPorTipoResponse")]
        DiretorSkinner.Grafo.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[] ListarRepetenciaPorTipo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarRepetenciaPorTipo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarRepetenciaPorTipoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[]> ListarRepetenciaPorTipoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalasDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalasDeAulaResponse")]
        DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[] ListarSalasDeAula();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalasDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalasDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[]> ListarSalasDeAulaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaResponse")]
        DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto ListarSalaDeAula(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto> ListarSalaDeAulaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorPessoaResponse")]
        DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorPessoa(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorPessoaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorPessoaAsync(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorDisciplinaRespo" +
            "nse")]
        DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorDisciplina(DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorDisciplinaRespo" +
            "nse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorDisciplinaAsync(DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorConceitoRespons" +
            "e")]
        DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorConceito(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorConceitoRespons" +
            "e")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorConceitoAsync(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorTurma", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorTurmaResponse")]
        DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorTurma(DiretorSkinner.Grafo.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorTurma", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorTurmaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorTurmaAsync(DiretorSkinner.Grafo.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorFiltros", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorFiltrosResponse" +
            "")]
        DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorFiltros(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito, DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina, DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa, DiretorSkinner.Grafo.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorFiltros", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarSalaDeAulaPorFiltrosResponse" +
            "")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorFiltrosAsync(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito, DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina, DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa, DiretorSkinner.Grafo.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarSalaDeAulaResponse")]
        void SalvarSalaDeAula(DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto SalaDeAula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarSalaDeAulaResponse")]
        System.Threading.Tasks.Task SalvarSalaDeAulaAsync(DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto SalaDeAula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarSalaDeAulaResponse")]
        void DeletarSalaDeAula(DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto SalaDeAula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarSalaDeAulaResponse")]
        System.Threading.Tasks.Task DeletarSalaDeAulaAsync(DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto SalaDeAula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTiposDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTiposDisciplinaResponse")]
        DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto[] ListarTiposDisciplina();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTiposDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTiposDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto[]> ListarTiposDisciplinaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTipoDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTipoDisciplinaResponse")]
        DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto ListarTipoDisciplina(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTipoDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTipoDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto> ListarTipoDisciplinaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarTipoDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarTipoDisciplinaResponse")]
        void SalvarTipoDisciplina(DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto tipoDisciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarTipoDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarTipoDisciplinaResponse")]
        System.Threading.Tasks.Task SalvarTipoDisciplinaAsync(DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto tipoDisciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarTipoDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarTipoDisciplinaResponse")]
        void DeletarTipoDisciplina(DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto tipoDisciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarTipoDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarTipoDisciplinaResponse")]
        System.Threading.Tasks.Task DeletarTipoDisciplinaAsync(DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto tipoDisciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTiposPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTiposPessoaResponse")]
        DiretorSkinner.Grafo.Tranporte.TipoPessoaDto[] ListarTiposPessoa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTiposPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTiposPessoaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.TipoPessoaDto[]> ListarTiposPessoaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTipoPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTipoPessoaResponse")]
        DiretorSkinner.Grafo.Tranporte.TipoPessoaDto ListarTipoPessoa(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTipoPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTipoPessoaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.TipoPessoaDto> ListarTipoPessoaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTipoPessoaPorPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTipoPessoaPorPessoaResponse")]
        DiretorSkinner.Grafo.Tranporte.TipoPessoaDto[] ListarTipoPessoaPorPessoa(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTipoPessoaPorPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTipoPessoaPorPessoaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.TipoPessoaDto[]> ListarTipoPessoaPorPessoaAsync(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarTipoPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarTipoPessoaResponse")]
        void SalvarTipoPessoa(DiretorSkinner.Grafo.Tranporte.TipoPessoaDto tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarTipoPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarTipoPessoaResponse")]
        System.Threading.Tasks.Task SalvarTipoPessoaAsync(DiretorSkinner.Grafo.Tranporte.TipoPessoaDto tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarTipoPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarTipoPessoaResponse")]
        void DeletarTipoPessoa(DiretorSkinner.Grafo.Tranporte.TipoPessoaDto tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarTipoPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarTipoPessoaResponse")]
        System.Threading.Tasks.Task DeletarTipoPessoaAsync(DiretorSkinner.Grafo.Tranporte.TipoPessoaDto tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTurmas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTurmasResponse")]
        DiretorSkinner.Grafo.Tranporte.TurmaDto[] ListarTurmas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTurmas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/ListarTurmasResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.TurmaDto[]> ListarTurmasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarTurma", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarTurmaResponse")]
        void SalvarTurma(DiretorSkinner.Grafo.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarTurma", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/SalvarTurmaResponse")]
        System.Threading.Tasks.Task SalvarTurmaAsync(DiretorSkinner.Grafo.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarTurma", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarTurmaResponse")]
        void DeletarTurma(DiretorSkinner.Grafo.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarTurma", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocioGrafo/DeletarTurmaResponse")]
        System.Threading.Tasks.Task DeletarTurmaAsync(DiretorSkinner.Grafo.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerGrafo/GetData", ReplyAction="http://tempuri.org/IDiretorSkinnerGrafo/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerGrafo/GetData", ReplyAction="http://tempuri.org/IDiretorSkinnerGrafo/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiretorSkinnerGrafoChannel : DiretorSkinner.Grafo.Seymour.IDiretorSkinnerGrafo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiretorSkinnerGrafoClient : System.ServiceModel.ClientBase<DiretorSkinner.Grafo.Seymour.IDiretorSkinnerGrafo>, DiretorSkinner.Grafo.Seymour.IDiretorSkinnerGrafo {
        
        public DiretorSkinnerGrafoClient() {
        }
        
        public DiretorSkinnerGrafoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiretorSkinnerGrafoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiretorSkinnerGrafoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiretorSkinnerGrafoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DiretorSkinner.Grafo.Tranporte.ConceitoDto[] ListarConceitos() {
            return base.Channel.ListarConceitos();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ConceitoDto[]> ListarConceitosAsync() {
            return base.Channel.ListarConceitosAsync();
        }
        
        public DiretorSkinner.Grafo.Tranporte.ConceitoDto ListarConceito(int id) {
            return base.Channel.ListarConceito(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ConceitoDto> ListarConceitoAsync(int id) {
            return base.Channel.ListarConceitoAsync(id);
        }
        
        public void SalvarConceito(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito) {
            base.Channel.SalvarConceito(conceito);
        }
        
        public System.Threading.Tasks.Task SalvarConceitoAsync(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito) {
            return base.Channel.SalvarConceitoAsync(conceito);
        }
        
        public void DeletarConceito(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito) {
            base.Channel.DeletarConceito(conceito);
        }
        
        public System.Threading.Tasks.Task DeletarConceitoAsync(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito) {
            return base.Channel.DeletarConceitoAsync(conceito);
        }
        
        public DiretorSkinner.Grafo.Tranporte.DisciplinaDto[] ListarDisciplinas() {
            return base.Channel.ListarDisciplinas();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.DisciplinaDto[]> ListarDisciplinasAsync() {
            return base.Channel.ListarDisciplinasAsync();
        }
        
        public DiretorSkinner.Grafo.Tranporte.DisciplinaDto[] ListarDisciplinaPorTipo(DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto tipoDisciplina) {
            return base.Channel.ListarDisciplinaPorTipo(tipoDisciplina);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.DisciplinaDto[]> ListarDisciplinaPorTipoAsync(DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto tipoDisciplina) {
            return base.Channel.ListarDisciplinaPorTipoAsync(tipoDisciplina);
        }
        
        public DiretorSkinner.Grafo.Tranporte.DisciplinaDto ListarDisciplina(int id) {
            return base.Channel.ListarDisciplina(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.DisciplinaDto> ListarDisciplinaAsync(int id) {
            return base.Channel.ListarDisciplinaAsync(id);
        }
        
        public void SalvarDisciplina(DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina) {
            base.Channel.SalvarDisciplina(disciplina);
        }
        
        public System.Threading.Tasks.Task SalvarDisciplinaAsync(DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina) {
            return base.Channel.SalvarDisciplinaAsync(disciplina);
        }
        
        public void DeletarDisciplina(DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina) {
            base.Channel.DeletarDisciplina(disciplina);
        }
        
        public System.Threading.Tasks.Task DeletarDisciplinaAsync(DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina) {
            return base.Channel.DeletarDisciplinaAsync(disciplina);
        }
        
        public DiretorSkinner.Grafo.Tranporte.PessoaDto[] ListarPessoas() {
            return base.Channel.ListarPessoas();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaDto[]> ListarPessoasAsync() {
            return base.Channel.ListarPessoasAsync();
        }
        
        public DiretorSkinner.Grafo.Tranporte.PessoaDto[] ListarPessoasPesquisa(string filtro) {
            return base.Channel.ListarPessoasPesquisa(filtro);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaDto[]> ListarPessoasPesquisaAsync(string filtro) {
            return base.Channel.ListarPessoasPesquisaAsync(filtro);
        }
        
        public DiretorSkinner.Grafo.Tranporte.PessoaDto[] ListarPessoaPorTipo(DiretorSkinner.Grafo.Tranporte.TipoPessoaDto tipoPessoa) {
            return base.Channel.ListarPessoaPorTipo(tipoPessoa);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaDto[]> ListarPessoaPorTipoAsync(DiretorSkinner.Grafo.Tranporte.TipoPessoaDto tipoPessoa) {
            return base.Channel.ListarPessoaPorTipoAsync(tipoPessoa);
        }
        
        public DiretorSkinner.Grafo.Tranporte.PessoaDto ListarPessoa(int id) {
            return base.Channel.ListarPessoa(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaDto> ListarPessoaAsync(int id) {
            return base.Channel.ListarPessoaAsync(id);
        }
        
        public DiretorSkinner.Grafo.Tranporte.PessoaDto ListarPessoaPorApelido(string apelido) {
            return base.Channel.ListarPessoaPorApelido(apelido);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaDto> ListarPessoaPorApelidoAsync(string apelido) {
            return base.Channel.ListarPessoaPorApelidoAsync(apelido);
        }
        
        public DiretorSkinner.Grafo.Tranporte.PessoaDto ListarPessoaPorCodigo(string codigo) {
            return base.Channel.ListarPessoaPorCodigo(codigo);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaDto> ListarPessoaPorCodigoAsync(string codigo) {
            return base.Channel.ListarPessoaPorCodigoAsync(codigo);
        }
        
        public void SalvarPessoa(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa) {
            base.Channel.SalvarPessoa(pessoa);
        }
        
        public System.Threading.Tasks.Task SalvarPessoaAsync(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa) {
            return base.Channel.SalvarPessoaAsync(pessoa);
        }
        
        public void DeletarPessoa(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa) {
            base.Channel.DeletarPessoa(pessoa);
        }
        
        public System.Threading.Tasks.Task DeletarPessoaAsync(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa) {
            return base.Channel.DeletarPessoaAsync(pessoa);
        }
        
        public DiretorSkinner.Grafo.Tranporte.PessoaPorConceitoDto[] ListarPessoaPorTodosConceitos() {
            return base.Channel.ListarPessoaPorTodosConceitos();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaPorConceitoDto[]> ListarPessoaPorTodosConceitosAsync() {
            return base.Channel.ListarPessoaPorTodosConceitosAsync();
        }
        
        public DiretorSkinner.Grafo.Tranporte.PessoaPorConceitoDto[] ListarPessoaPorConceito(int id) {
            return base.Channel.ListarPessoaPorConceito(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.PessoaPorConceitoDto[]> ListarPessoaPorConceitoAsync(int id) {
            return base.Channel.ListarPessoaPorConceitoAsync(id);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaInserirConceito(int tamanho) {
            return base.Channel.CargaInserirConceito(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaInserirConceitoAsync(int tamanho) {
            return base.Channel.CargaInserirConceitoAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaAlterarConceito(int tamanho) {
            return base.Channel.CargaAlterarConceito(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaAlterarConceitoAsync(int tamanho) {
            return base.Channel.CargaAlterarConceitoAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaExcluirConceito(int tamanho) {
            return base.Channel.CargaExcluirConceito(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaExcluirConceitoAsync(int tamanho) {
            return base.Channel.CargaExcluirConceitoAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaSelecionarConceito(int tamanho) {
            return base.Channel.CargaSelecionarConceito(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaSelecionarConceitoAsync(int tamanho) {
            return base.Channel.CargaSelecionarConceitoAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaRelatorioConceito(int tamanho) {
            return base.Channel.CargaRelatorioConceito(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaRelatorioConceitoAsync(int tamanho) {
            return base.Channel.CargaRelatorioConceitoAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaInserirDisciplina(int tamanho) {
            return base.Channel.CargaInserirDisciplina(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaInserirDisciplinaAsync(int tamanho) {
            return base.Channel.CargaInserirDisciplinaAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaAlterarDisciplina(int tamanho) {
            return base.Channel.CargaAlterarDisciplina(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaAlterarDisciplinaAsync(int tamanho) {
            return base.Channel.CargaAlterarDisciplinaAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaExcluirDisciplina(int tamanho) {
            return base.Channel.CargaExcluirDisciplina(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaExcluirDisciplinaAsync(int tamanho) {
            return base.Channel.CargaExcluirDisciplinaAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaSelecionarDisciplina(int tamanho) {
            return base.Channel.CargaSelecionarDisciplina(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaSelecionarDisciplinaAsync(int tamanho) {
            return base.Channel.CargaSelecionarDisciplinaAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaRelatorioDisciplina(int tamanho) {
            return base.Channel.CargaRelatorioDisciplina(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaRelatorioDisciplinaAsync(int tamanho) {
            return base.Channel.CargaRelatorioDisciplinaAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaInserirSalaDeAula(int tamanho) {
            return base.Channel.CargaInserirSalaDeAula(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaInserirSalaDeAulaAsync(int tamanho) {
            return base.Channel.CargaInserirSalaDeAulaAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaAlterarSalaDeAula(int tamanho) {
            return base.Channel.CargaAlterarSalaDeAula(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaAlterarSalaDeAulaAsync(int tamanho) {
            return base.Channel.CargaAlterarSalaDeAulaAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaExcluirSalaDeAula(int tamanho) {
            return base.Channel.CargaExcluirSalaDeAula(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaExcluirSalaDeAulaAsync(int tamanho) {
            return base.Channel.CargaExcluirSalaDeAulaAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaSelecionarSalaDeAula(int tamanho) {
            return base.Channel.CargaSelecionarSalaDeAula(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaSelecionarSalaDeAulaAsync(int tamanho) {
            return base.Channel.CargaSelecionarSalaDeAulaAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.ProcessamentoDto CargaRelatorioSalaDeAula(int tamanho) {
            return base.Channel.CargaRelatorioSalaDeAula(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.ProcessamentoDto> CargaRelatorioSalaDeAulaAsync(int tamanho) {
            return base.Channel.CargaRelatorioSalaDeAulaAsync(tamanho);
        }
        
        public DiretorSkinner.Grafo.Tranporte.QtdePessoaPorDisciplinaDto[] ListarQtdePessoaPorTodasDisciplinas() {
            return base.Channel.ListarQtdePessoaPorTodasDisciplinas();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.QtdePessoaPorDisciplinaDto[]> ListarQtdePessoaPorTodasDisciplinasAsync() {
            return base.Channel.ListarQtdePessoaPorTodasDisciplinasAsync();
        }
        
        public DiretorSkinner.Grafo.Tranporte.QtdePessoaPorDisciplinaDto[] ListarQtdePessoaPorDisciplina(int id) {
            return base.Channel.ListarQtdePessoaPorDisciplina(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.QtdePessoaPorDisciplinaDto[]> ListarQtdePessoaPorDisciplinaAsync(int id) {
            return base.Channel.ListarQtdePessoaPorDisciplinaAsync(id);
        }
        
        public DiretorSkinner.Grafo.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[] ListarRepetenciaPorTodosTipos() {
            return base.Channel.ListarRepetenciaPorTodosTipos();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[]> ListarRepetenciaPorTodosTiposAsync() {
            return base.Channel.ListarRepetenciaPorTodosTiposAsync();
        }
        
        public DiretorSkinner.Grafo.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[] ListarRepetenciaPorTipo(int id) {
            return base.Channel.ListarRepetenciaPorTipo(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[]> ListarRepetenciaPorTipoAsync(int id) {
            return base.Channel.ListarRepetenciaPorTipoAsync(id);
        }
        
        public DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[] ListarSalasDeAula() {
            return base.Channel.ListarSalasDeAula();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[]> ListarSalasDeAulaAsync() {
            return base.Channel.ListarSalasDeAulaAsync();
        }
        
        public DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto ListarSalaDeAula(int id) {
            return base.Channel.ListarSalaDeAula(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto> ListarSalaDeAulaAsync(int id) {
            return base.Channel.ListarSalaDeAulaAsync(id);
        }
        
        public DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorPessoa(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa) {
            return base.Channel.ListarSalaDeAulaPorPessoa(pessoa);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorPessoaAsync(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa) {
            return base.Channel.ListarSalaDeAulaPorPessoaAsync(pessoa);
        }
        
        public DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorDisciplina(DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina) {
            return base.Channel.ListarSalaDeAulaPorDisciplina(disciplina);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorDisciplinaAsync(DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina) {
            return base.Channel.ListarSalaDeAulaPorDisciplinaAsync(disciplina);
        }
        
        public DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorConceito(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito) {
            return base.Channel.ListarSalaDeAulaPorConceito(conceito);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorConceitoAsync(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito) {
            return base.Channel.ListarSalaDeAulaPorConceitoAsync(conceito);
        }
        
        public DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorTurma(DiretorSkinner.Grafo.Tranporte.TurmaDto turma) {
            return base.Channel.ListarSalaDeAulaPorTurma(turma);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorTurmaAsync(DiretorSkinner.Grafo.Tranporte.TurmaDto turma) {
            return base.Channel.ListarSalaDeAulaPorTurmaAsync(turma);
        }
        
        public DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorFiltros(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito, DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina, DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa, DiretorSkinner.Grafo.Tranporte.TurmaDto turma) {
            return base.Channel.ListarSalaDeAulaPorFiltros(conceito, disciplina, pessoa, turma);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorFiltrosAsync(DiretorSkinner.Grafo.Tranporte.ConceitoDto conceito, DiretorSkinner.Grafo.Tranporte.DisciplinaDto disciplina, DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa, DiretorSkinner.Grafo.Tranporte.TurmaDto turma) {
            return base.Channel.ListarSalaDeAulaPorFiltrosAsync(conceito, disciplina, pessoa, turma);
        }
        
        public void SalvarSalaDeAula(DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto SalaDeAula) {
            base.Channel.SalvarSalaDeAula(SalaDeAula);
        }
        
        public System.Threading.Tasks.Task SalvarSalaDeAulaAsync(DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto SalaDeAula) {
            return base.Channel.SalvarSalaDeAulaAsync(SalaDeAula);
        }
        
        public void DeletarSalaDeAula(DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto SalaDeAula) {
            base.Channel.DeletarSalaDeAula(SalaDeAula);
        }
        
        public System.Threading.Tasks.Task DeletarSalaDeAulaAsync(DiretorSkinner.Grafo.Tranporte.SalaDeAulaDto SalaDeAula) {
            return base.Channel.DeletarSalaDeAulaAsync(SalaDeAula);
        }
        
        public DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto[] ListarTiposDisciplina() {
            return base.Channel.ListarTiposDisciplina();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto[]> ListarTiposDisciplinaAsync() {
            return base.Channel.ListarTiposDisciplinaAsync();
        }
        
        public DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto ListarTipoDisciplina(int id) {
            return base.Channel.ListarTipoDisciplina(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto> ListarTipoDisciplinaAsync(int id) {
            return base.Channel.ListarTipoDisciplinaAsync(id);
        }
        
        public void SalvarTipoDisciplina(DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto tipoDisciplina) {
            base.Channel.SalvarTipoDisciplina(tipoDisciplina);
        }
        
        public System.Threading.Tasks.Task SalvarTipoDisciplinaAsync(DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto tipoDisciplina) {
            return base.Channel.SalvarTipoDisciplinaAsync(tipoDisciplina);
        }
        
        public void DeletarTipoDisciplina(DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto tipoDisciplina) {
            base.Channel.DeletarTipoDisciplina(tipoDisciplina);
        }
        
        public System.Threading.Tasks.Task DeletarTipoDisciplinaAsync(DiretorSkinner.Grafo.Tranporte.TipoDisciplinaDto tipoDisciplina) {
            return base.Channel.DeletarTipoDisciplinaAsync(tipoDisciplina);
        }
        
        public DiretorSkinner.Grafo.Tranporte.TipoPessoaDto[] ListarTiposPessoa() {
            return base.Channel.ListarTiposPessoa();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.TipoPessoaDto[]> ListarTiposPessoaAsync() {
            return base.Channel.ListarTiposPessoaAsync();
        }
        
        public DiretorSkinner.Grafo.Tranporte.TipoPessoaDto ListarTipoPessoa(int id) {
            return base.Channel.ListarTipoPessoa(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.TipoPessoaDto> ListarTipoPessoaAsync(int id) {
            return base.Channel.ListarTipoPessoaAsync(id);
        }
        
        public DiretorSkinner.Grafo.Tranporte.TipoPessoaDto[] ListarTipoPessoaPorPessoa(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa) {
            return base.Channel.ListarTipoPessoaPorPessoa(pessoa);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.TipoPessoaDto[]> ListarTipoPessoaPorPessoaAsync(DiretorSkinner.Grafo.Tranporte.PessoaDto pessoa) {
            return base.Channel.ListarTipoPessoaPorPessoaAsync(pessoa);
        }
        
        public void SalvarTipoPessoa(DiretorSkinner.Grafo.Tranporte.TipoPessoaDto tipoPessoa) {
            base.Channel.SalvarTipoPessoa(tipoPessoa);
        }
        
        public System.Threading.Tasks.Task SalvarTipoPessoaAsync(DiretorSkinner.Grafo.Tranporte.TipoPessoaDto tipoPessoa) {
            return base.Channel.SalvarTipoPessoaAsync(tipoPessoa);
        }
        
        public void DeletarTipoPessoa(DiretorSkinner.Grafo.Tranporte.TipoPessoaDto tipoPessoa) {
            base.Channel.DeletarTipoPessoa(tipoPessoa);
        }
        
        public System.Threading.Tasks.Task DeletarTipoPessoaAsync(DiretorSkinner.Grafo.Tranporte.TipoPessoaDto tipoPessoa) {
            return base.Channel.DeletarTipoPessoaAsync(tipoPessoa);
        }
        
        public DiretorSkinner.Grafo.Tranporte.TurmaDto[] ListarTurmas() {
            return base.Channel.ListarTurmas();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Grafo.Tranporte.TurmaDto[]> ListarTurmasAsync() {
            return base.Channel.ListarTurmasAsync();
        }
        
        public void SalvarTurma(DiretorSkinner.Grafo.Tranporte.TurmaDto turma) {
            base.Channel.SalvarTurma(turma);
        }
        
        public System.Threading.Tasks.Task SalvarTurmaAsync(DiretorSkinner.Grafo.Tranporte.TurmaDto turma) {
            return base.Channel.SalvarTurmaAsync(turma);
        }
        
        public void DeletarTurma(DiretorSkinner.Grafo.Tranporte.TurmaDto turma) {
            base.Channel.DeletarTurma(turma);
        }
        
        public System.Threading.Tasks.Task DeletarTurmaAsync(DiretorSkinner.Grafo.Tranporte.TurmaDto turma) {
            return base.Channel.DeletarTurmaAsync(turma);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
    }
}
