//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiretorSkinner.Seymour {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Seymour.IDiretorSkinner")]
    public interface IDiretorSkinner {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorTodosConceitos", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorTodosConceitosResponse")]
        DiretorSkinner.Tranporte.PessoaPorConceitoDto[] ListarPessoaPorTodosConceitos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorTodosConceitos", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorTodosConceitosResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaPorConceitoDto[]> ListarPessoaPorTodosConceitosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorConceitoResponse")]
        DiretorSkinner.Tranporte.PessoaPorConceitoDto[] ListarPessoaPorConceito(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaPorConceitoDto[]> ListarPessoaPorConceitoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaInserirConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaInserirConceitoResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaInserirConceito(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaInserirConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaInserirConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaInserirConceitoAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaAlterarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaAlterarConceitoResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaAlterarConceito(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaAlterarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaAlterarConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaAlterarConceitoAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaExcluirConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaExcluirConceitoResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaExcluirConceito(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaExcluirConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaExcluirConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaExcluirConceitoAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaSelecionarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaSelecionarConceitoResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaSelecionarConceito(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaSelecionarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaSelecionarConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaSelecionarConceitoAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaRelatorioConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaRelatorioConceitoResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaRelatorioConceito(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaRelatorioConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaRelatorioConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaRelatorioConceitoAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaInserirDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaInserirDisciplinaResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaInserirDisciplina(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaInserirDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaInserirDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaInserirDisciplinaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaAlterarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaAlterarDisciplinaResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaAlterarDisciplina(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaAlterarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaAlterarDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaAlterarDisciplinaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaExcluirDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaExcluirDisciplinaResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaExcluirDisciplina(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaExcluirDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaExcluirDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaExcluirDisciplinaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaSelecionarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaSelecionarDisciplinaResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaSelecionarDisciplina(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaSelecionarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaSelecionarDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaSelecionarDisciplinaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaRelatorioDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaRelatorioDisciplinaResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaRelatorioDisciplina(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaRelatorioDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaRelatorioDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaRelatorioDisciplinaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaInserirSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaInserirSalaDeAulaResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaInserirSalaDeAula(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaInserirSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaInserirSalaDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaInserirSalaDeAulaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaAlterarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaAlterarSalaDeAulaResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaAlterarSalaDeAula(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaAlterarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaAlterarSalaDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaAlterarSalaDeAulaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaExcluirSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaExcluirSalaDeAulaResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaExcluirSalaDeAula(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaExcluirSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaExcluirSalaDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaExcluirSalaDeAulaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaSelecionarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaSelecionarSalaDeAulaResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaSelecionarSalaDeAula(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaSelecionarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaSelecionarSalaDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaSelecionarSalaDeAulaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaRelatorioSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaRelatorioSalaDeAulaResponse")]
        DiretorSkinner.Tranporte.ProcessamentoDto CargaRelatorioSalaDeAula(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/CargaRelatorioSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/CargaRelatorioSalaDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaRelatorioSalaDeAulaAsync(int tamanho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoasResponse")]
        DiretorSkinner.Tranporte.PessoaDto[] ListarPessoas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoasResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaDto[]> ListarPessoasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoasPesquisa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoasPesquisaResponse")]
        DiretorSkinner.Tranporte.PessoaDto[] ListarPessoasPesquisa(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoasPesquisa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoasPesquisaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaDto[]> ListarPessoasPesquisaAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorTipo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorTipoResponse")]
        DiretorSkinner.Tranporte.PessoaDto[] ListarPessoaPorTipo(DiretorSkinner.Tranporte.TipoPessoaDto tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorTipo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorTipoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaDto[]> ListarPessoaPorTipoAsync(DiretorSkinner.Tranporte.TipoPessoaDto tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaResponse")]
        DiretorSkinner.Tranporte.PessoaDto ListarPessoa(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaDto> ListarPessoaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorApelido", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorApelidoResponse")]
        DiretorSkinner.Tranporte.PessoaDto ListarPessoaPorApelido(string apelido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorApelido", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorApelidoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaDto> ListarPessoaPorApelidoAsync(string apelido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorCodigo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorCodigoResponse")]
        DiretorSkinner.Tranporte.PessoaDto ListarPessoaPorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorCodigo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarPessoaPorCodigoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaDto> ListarPessoaPorCodigoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarPessoaResponse")]
        void SalvarPessoa(DiretorSkinner.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarPessoaResponse")]
        System.Threading.Tasks.Task SalvarPessoaAsync(DiretorSkinner.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarPessoaResponse")]
        void DeletarPessoa(DiretorSkinner.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarPessoaResponse")]
        System.Threading.Tasks.Task DeletarPessoaAsync(DiretorSkinner.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarQtdePessoaPorTodasDisciplinas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarQtdePessoaPorTodasDisciplinasResp" +
            "onse")]
        DiretorSkinner.Tranporte.QtdePessoaPorDisciplinaDto[] ListarQtdePessoaPorTodasDisciplinas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarQtdePessoaPorTodasDisciplinas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarQtdePessoaPorTodasDisciplinasResp" +
            "onse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.QtdePessoaPorDisciplinaDto[]> ListarQtdePessoaPorTodasDisciplinasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarQtdePessoaPorDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarQtdePessoaPorDisciplinaResponse")]
        DiretorSkinner.Tranporte.QtdePessoaPorDisciplinaDto[] ListarQtdePessoaPorDisciplina(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarQtdePessoaPorDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarQtdePessoaPorDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.QtdePessoaPorDisciplinaDto[]> ListarQtdePessoaPorDisciplinaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarRepetenciaPorTodosTipos", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarRepetenciaPorTodosTiposResponse")]
        DiretorSkinner.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[] ListarRepetenciaPorTodosTipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarRepetenciaPorTodosTipos", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarRepetenciaPorTodosTiposResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[]> ListarRepetenciaPorTodosTiposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarRepetenciaPorTipo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarRepetenciaPorTipoResponse")]
        DiretorSkinner.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[] ListarRepetenciaPorTipo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarRepetenciaPorTipo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarRepetenciaPorTipoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[]> ListarRepetenciaPorTipoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalasDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalasDeAulaResponse")]
        DiretorSkinner.Tranporte.SalaDeAulaDto[] ListarSalasDeAula();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalasDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalasDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto[]> ListarSalasDeAulaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaResponse")]
        DiretorSkinner.Tranporte.SalaDeAulaDto ListarSalaDeAula(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto> ListarSalaDeAulaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorPessoaResponse")]
        DiretorSkinner.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorPessoa(DiretorSkinner.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorPessoaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorPessoaAsync(DiretorSkinner.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorDisciplinaResponse")]
        DiretorSkinner.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorDisciplina(DiretorSkinner.Tranporte.DisciplinaDto disciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorDisciplinaAsync(DiretorSkinner.Tranporte.DisciplinaDto disciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorConceitoResponse")]
        DiretorSkinner.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorConceito(DiretorSkinner.Tranporte.ConceitoDto conceito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorConceitoAsync(DiretorSkinner.Tranporte.ConceitoDto conceito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorTurma", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorTurmaResponse")]
        DiretorSkinner.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorTurma(DiretorSkinner.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorTurma", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorTurmaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorTurmaAsync(DiretorSkinner.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorFiltros", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorFiltrosResponse")]
        DiretorSkinner.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorFiltros(DiretorSkinner.Tranporte.ConceitoDto conceito, DiretorSkinner.Tranporte.DisciplinaDto disciplina, DiretorSkinner.Tranporte.PessoaDto pessoa, DiretorSkinner.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorFiltros", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarSalaDeAulaPorFiltrosResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorFiltrosAsync(DiretorSkinner.Tranporte.ConceitoDto conceito, DiretorSkinner.Tranporte.DisciplinaDto disciplina, DiretorSkinner.Tranporte.PessoaDto pessoa, DiretorSkinner.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarSalaDeAulaResponse")]
        void SalvarSalaDeAula(DiretorSkinner.Tranporte.SalaDeAulaDto SalaDeAula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarSalaDeAulaResponse")]
        System.Threading.Tasks.Task SalvarSalaDeAulaAsync(DiretorSkinner.Tranporte.SalaDeAulaDto SalaDeAula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarSalaDeAulaResponse")]
        void DeletarSalaDeAula(DiretorSkinner.Tranporte.SalaDeAulaDto SalaDeAula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarSalaDeAula", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarSalaDeAulaResponse")]
        System.Threading.Tasks.Task DeletarSalaDeAulaAsync(DiretorSkinner.Tranporte.SalaDeAulaDto SalaDeAula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarTurmas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarTurmasResponse")]
        DiretorSkinner.Tranporte.TurmaDto[] ListarTurmas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarTurmas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarTurmasResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.TurmaDto[]> ListarTurmasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarTurma", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarTurmaResponse")]
        void SalvarTurma(DiretorSkinner.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarTurma", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarTurmaResponse")]
        System.Threading.Tasks.Task SalvarTurmaAsync(DiretorSkinner.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarTurma", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarTurmaResponse")]
        void DeletarTurma(DiretorSkinner.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarTurma", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarTurmaResponse")]
        System.Threading.Tasks.Task DeletarTurmaAsync(DiretorSkinner.Tranporte.TurmaDto turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarTiposPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarTiposPessoaResponse")]
        DiretorSkinner.Tranporte.TipoPessoaDto[] ListarTiposPessoa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarTiposPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarTiposPessoaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.TipoPessoaDto[]> ListarTiposPessoaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarTipoPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarTipoPessoaResponse")]
        DiretorSkinner.Tranporte.TipoPessoaDto ListarTipoPessoa(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarTipoPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarTipoPessoaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.TipoPessoaDto> ListarTipoPessoaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarTipoPessoaPorPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarTipoPessoaPorPessoaResponse")]
        DiretorSkinner.Tranporte.TipoPessoaDto[] ListarTipoPessoaPorPessoa(DiretorSkinner.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarTipoPessoaPorPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarTipoPessoaPorPessoaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.TipoPessoaDto[]> ListarTipoPessoaPorPessoaAsync(DiretorSkinner.Tranporte.PessoaDto pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarTipoPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarTipoPessoaResponse")]
        void SalvarTipoPessoa(DiretorSkinner.Tranporte.TipoPessoaDto tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarTipoPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarTipoPessoaResponse")]
        System.Threading.Tasks.Task SalvarTipoPessoaAsync(DiretorSkinner.Tranporte.TipoPessoaDto tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarTipoPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarTipoPessoaResponse")]
        void DeletarTipoPessoa(DiretorSkinner.Tranporte.TipoPessoaDto tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarTipoPessoa", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarTipoPessoaResponse")]
        System.Threading.Tasks.Task DeletarTipoPessoaAsync(DiretorSkinner.Tranporte.TipoPessoaDto tipoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarTiposDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarTiposDisciplinaResponse")]
        DiretorSkinner.Tranporte.TipoDisciplinaDto[] ListarTiposDisciplina();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarTiposDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarTiposDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.TipoDisciplinaDto[]> ListarTiposDisciplinaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarTipoDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarTipoDisciplinaResponse")]
        DiretorSkinner.Tranporte.TipoDisciplinaDto ListarTipoDisciplina(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarTipoDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarTipoDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.TipoDisciplinaDto> ListarTipoDisciplinaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarTipoDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarTipoDisciplinaResponse")]
        void SalvarTipoDisciplina(DiretorSkinner.Tranporte.TipoDisciplinaDto tipoDisciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarTipoDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarTipoDisciplinaResponse")]
        System.Threading.Tasks.Task SalvarTipoDisciplinaAsync(DiretorSkinner.Tranporte.TipoDisciplinaDto tipoDisciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarTipoDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarTipoDisciplinaResponse")]
        void DeletarTipoDisciplina(DiretorSkinner.Tranporte.TipoDisciplinaDto tipoDisciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarTipoDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarTipoDisciplinaResponse")]
        System.Threading.Tasks.Task DeletarTipoDisciplinaAsync(DiretorSkinner.Tranporte.TipoDisciplinaDto tipoDisciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarDisciplinas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarDisciplinasResponse")]
        DiretorSkinner.Tranporte.DisciplinaDto[] ListarDisciplinas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarDisciplinas", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarDisciplinasResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.DisciplinaDto[]> ListarDisciplinasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarDisciplinaPorTipo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarDisciplinaPorTipoResponse")]
        DiretorSkinner.Tranporte.DisciplinaDto[] ListarDisciplinaPorTipo(DiretorSkinner.Tranporte.TipoDisciplinaDto tipoDisciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarDisciplinaPorTipo", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarDisciplinaPorTipoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.DisciplinaDto[]> ListarDisciplinaPorTipoAsync(DiretorSkinner.Tranporte.TipoDisciplinaDto tipoDisciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarDisciplinaResponse")]
        DiretorSkinner.Tranporte.DisciplinaDto ListarDisciplina(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarDisciplinaResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.DisciplinaDto> ListarDisciplinaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarDisciplinaResponse")]
        void SalvarDisciplina(DiretorSkinner.Tranporte.DisciplinaDto disciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarDisciplinaResponse")]
        System.Threading.Tasks.Task SalvarDisciplinaAsync(DiretorSkinner.Tranporte.DisciplinaDto disciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarDisciplinaResponse")]
        void DeletarDisciplina(DiretorSkinner.Tranporte.DisciplinaDto disciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarDisciplina", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarDisciplinaResponse")]
        System.Threading.Tasks.Task DeletarDisciplinaAsync(DiretorSkinner.Tranporte.DisciplinaDto disciplina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarConceitos", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarConceitosResponse")]
        DiretorSkinner.Tranporte.ConceitoDto[] ListarConceitos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarConceitos", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarConceitosResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ConceitoDto[]> ListarConceitosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarConceitoResponse")]
        DiretorSkinner.Tranporte.ConceitoDto ListarConceito(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/ListarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/ListarConceitoResponse")]
        System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ConceitoDto> ListarConceitoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarConceitoResponse")]
        void SalvarConceito(DiretorSkinner.Tranporte.ConceitoDto conceito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/SalvarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/SalvarConceitoResponse")]
        System.Threading.Tasks.Task SalvarConceitoAsync(DiretorSkinner.Tranporte.ConceitoDto conceito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarConceitoResponse")]
        void DeletarConceito(DiretorSkinner.Tranporte.ConceitoDto conceito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinnerNegocio/DeletarConceito", ReplyAction="http://tempuri.org/IDiretorSkinnerNegocio/DeletarConceitoResponse")]
        System.Threading.Tasks.Task DeletarConceitoAsync(DiretorSkinner.Tranporte.ConceitoDto conceito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinner/GetData", ReplyAction="http://tempuri.org/IDiretorSkinner/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiretorSkinner/GetData", ReplyAction="http://tempuri.org/IDiretorSkinner/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiretorSkinnerChannel : DiretorSkinner.Seymour.IDiretorSkinner, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiretorSkinnerClient : System.ServiceModel.ClientBase<DiretorSkinner.Seymour.IDiretorSkinner>, DiretorSkinner.Seymour.IDiretorSkinner {
        
        public DiretorSkinnerClient() {
        }
        
        public DiretorSkinnerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiretorSkinnerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiretorSkinnerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiretorSkinnerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DiretorSkinner.Tranporte.PessoaPorConceitoDto[] ListarPessoaPorTodosConceitos() {
            return base.Channel.ListarPessoaPorTodosConceitos();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaPorConceitoDto[]> ListarPessoaPorTodosConceitosAsync() {
            return base.Channel.ListarPessoaPorTodosConceitosAsync();
        }
        
        public DiretorSkinner.Tranporte.PessoaPorConceitoDto[] ListarPessoaPorConceito(int id) {
            return base.Channel.ListarPessoaPorConceito(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaPorConceitoDto[]> ListarPessoaPorConceitoAsync(int id) {
            return base.Channel.ListarPessoaPorConceitoAsync(id);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaInserirConceito(int tamanho) {
            return base.Channel.CargaInserirConceito(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaInserirConceitoAsync(int tamanho) {
            return base.Channel.CargaInserirConceitoAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaAlterarConceito(int tamanho) {
            return base.Channel.CargaAlterarConceito(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaAlterarConceitoAsync(int tamanho) {
            return base.Channel.CargaAlterarConceitoAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaExcluirConceito(int tamanho) {
            return base.Channel.CargaExcluirConceito(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaExcluirConceitoAsync(int tamanho) {
            return base.Channel.CargaExcluirConceitoAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaSelecionarConceito(int tamanho) {
            return base.Channel.CargaSelecionarConceito(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaSelecionarConceitoAsync(int tamanho) {
            return base.Channel.CargaSelecionarConceitoAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaRelatorioConceito(int tamanho) {
            return base.Channel.CargaRelatorioConceito(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaRelatorioConceitoAsync(int tamanho) {
            return base.Channel.CargaRelatorioConceitoAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaInserirDisciplina(int tamanho) {
            return base.Channel.CargaInserirDisciplina(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaInserirDisciplinaAsync(int tamanho) {
            return base.Channel.CargaInserirDisciplinaAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaAlterarDisciplina(int tamanho) {
            return base.Channel.CargaAlterarDisciplina(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaAlterarDisciplinaAsync(int tamanho) {
            return base.Channel.CargaAlterarDisciplinaAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaExcluirDisciplina(int tamanho) {
            return base.Channel.CargaExcluirDisciplina(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaExcluirDisciplinaAsync(int tamanho) {
            return base.Channel.CargaExcluirDisciplinaAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaSelecionarDisciplina(int tamanho) {
            return base.Channel.CargaSelecionarDisciplina(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaSelecionarDisciplinaAsync(int tamanho) {
            return base.Channel.CargaSelecionarDisciplinaAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaRelatorioDisciplina(int tamanho) {
            return base.Channel.CargaRelatorioDisciplina(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaRelatorioDisciplinaAsync(int tamanho) {
            return base.Channel.CargaRelatorioDisciplinaAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaInserirSalaDeAula(int tamanho) {
            return base.Channel.CargaInserirSalaDeAula(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaInserirSalaDeAulaAsync(int tamanho) {
            return base.Channel.CargaInserirSalaDeAulaAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaAlterarSalaDeAula(int tamanho) {
            return base.Channel.CargaAlterarSalaDeAula(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaAlterarSalaDeAulaAsync(int tamanho) {
            return base.Channel.CargaAlterarSalaDeAulaAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaExcluirSalaDeAula(int tamanho) {
            return base.Channel.CargaExcluirSalaDeAula(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaExcluirSalaDeAulaAsync(int tamanho) {
            return base.Channel.CargaExcluirSalaDeAulaAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaSelecionarSalaDeAula(int tamanho) {
            return base.Channel.CargaSelecionarSalaDeAula(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaSelecionarSalaDeAulaAsync(int tamanho) {
            return base.Channel.CargaSelecionarSalaDeAulaAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.ProcessamentoDto CargaRelatorioSalaDeAula(int tamanho) {
            return base.Channel.CargaRelatorioSalaDeAula(tamanho);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ProcessamentoDto> CargaRelatorioSalaDeAulaAsync(int tamanho) {
            return base.Channel.CargaRelatorioSalaDeAulaAsync(tamanho);
        }
        
        public DiretorSkinner.Tranporte.PessoaDto[] ListarPessoas() {
            return base.Channel.ListarPessoas();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaDto[]> ListarPessoasAsync() {
            return base.Channel.ListarPessoasAsync();
        }
        
        public DiretorSkinner.Tranporte.PessoaDto[] ListarPessoasPesquisa(string filtro) {
            return base.Channel.ListarPessoasPesquisa(filtro);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaDto[]> ListarPessoasPesquisaAsync(string filtro) {
            return base.Channel.ListarPessoasPesquisaAsync(filtro);
        }
        
        public DiretorSkinner.Tranporte.PessoaDto[] ListarPessoaPorTipo(DiretorSkinner.Tranporte.TipoPessoaDto tipoPessoa) {
            return base.Channel.ListarPessoaPorTipo(tipoPessoa);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaDto[]> ListarPessoaPorTipoAsync(DiretorSkinner.Tranporte.TipoPessoaDto tipoPessoa) {
            return base.Channel.ListarPessoaPorTipoAsync(tipoPessoa);
        }
        
        public DiretorSkinner.Tranporte.PessoaDto ListarPessoa(int id) {
            return base.Channel.ListarPessoa(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaDto> ListarPessoaAsync(int id) {
            return base.Channel.ListarPessoaAsync(id);
        }
        
        public DiretorSkinner.Tranporte.PessoaDto ListarPessoaPorApelido(string apelido) {
            return base.Channel.ListarPessoaPorApelido(apelido);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaDto> ListarPessoaPorApelidoAsync(string apelido) {
            return base.Channel.ListarPessoaPorApelidoAsync(apelido);
        }
        
        public DiretorSkinner.Tranporte.PessoaDto ListarPessoaPorCodigo(string codigo) {
            return base.Channel.ListarPessoaPorCodigo(codigo);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.PessoaDto> ListarPessoaPorCodigoAsync(string codigo) {
            return base.Channel.ListarPessoaPorCodigoAsync(codigo);
        }
        
        public void SalvarPessoa(DiretorSkinner.Tranporte.PessoaDto pessoa) {
            base.Channel.SalvarPessoa(pessoa);
        }
        
        public System.Threading.Tasks.Task SalvarPessoaAsync(DiretorSkinner.Tranporte.PessoaDto pessoa) {
            return base.Channel.SalvarPessoaAsync(pessoa);
        }
        
        public void DeletarPessoa(DiretorSkinner.Tranporte.PessoaDto pessoa) {
            base.Channel.DeletarPessoa(pessoa);
        }
        
        public System.Threading.Tasks.Task DeletarPessoaAsync(DiretorSkinner.Tranporte.PessoaDto pessoa) {
            return base.Channel.DeletarPessoaAsync(pessoa);
        }
        
        public DiretorSkinner.Tranporte.QtdePessoaPorDisciplinaDto[] ListarQtdePessoaPorTodasDisciplinas() {
            return base.Channel.ListarQtdePessoaPorTodasDisciplinas();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.QtdePessoaPorDisciplinaDto[]> ListarQtdePessoaPorTodasDisciplinasAsync() {
            return base.Channel.ListarQtdePessoaPorTodasDisciplinasAsync();
        }
        
        public DiretorSkinner.Tranporte.QtdePessoaPorDisciplinaDto[] ListarQtdePessoaPorDisciplina(int id) {
            return base.Channel.ListarQtdePessoaPorDisciplina(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.QtdePessoaPorDisciplinaDto[]> ListarQtdePessoaPorDisciplinaAsync(int id) {
            return base.Channel.ListarQtdePessoaPorDisciplinaAsync(id);
        }
        
        public DiretorSkinner.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[] ListarRepetenciaPorTodosTipos() {
            return base.Channel.ListarRepetenciaPorTodosTipos();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[]> ListarRepetenciaPorTodosTiposAsync() {
            return base.Channel.ListarRepetenciaPorTodosTiposAsync();
        }
        
        public DiretorSkinner.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[] ListarRepetenciaPorTipo(int id) {
            return base.Channel.ListarRepetenciaPorTipo(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.RepetenciaDeDisciplinaPorTipoPessoaDto[]> ListarRepetenciaPorTipoAsync(int id) {
            return base.Channel.ListarRepetenciaPorTipoAsync(id);
        }
        
        public DiretorSkinner.Tranporte.SalaDeAulaDto[] ListarSalasDeAula() {
            return base.Channel.ListarSalasDeAula();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto[]> ListarSalasDeAulaAsync() {
            return base.Channel.ListarSalasDeAulaAsync();
        }
        
        public DiretorSkinner.Tranporte.SalaDeAulaDto ListarSalaDeAula(int id) {
            return base.Channel.ListarSalaDeAula(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto> ListarSalaDeAulaAsync(int id) {
            return base.Channel.ListarSalaDeAulaAsync(id);
        }
        
        public DiretorSkinner.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorPessoa(DiretorSkinner.Tranporte.PessoaDto pessoa) {
            return base.Channel.ListarSalaDeAulaPorPessoa(pessoa);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorPessoaAsync(DiretorSkinner.Tranporte.PessoaDto pessoa) {
            return base.Channel.ListarSalaDeAulaPorPessoaAsync(pessoa);
        }
        
        public DiretorSkinner.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorDisciplina(DiretorSkinner.Tranporte.DisciplinaDto disciplina) {
            return base.Channel.ListarSalaDeAulaPorDisciplina(disciplina);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorDisciplinaAsync(DiretorSkinner.Tranporte.DisciplinaDto disciplina) {
            return base.Channel.ListarSalaDeAulaPorDisciplinaAsync(disciplina);
        }
        
        public DiretorSkinner.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorConceito(DiretorSkinner.Tranporte.ConceitoDto conceito) {
            return base.Channel.ListarSalaDeAulaPorConceito(conceito);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorConceitoAsync(DiretorSkinner.Tranporte.ConceitoDto conceito) {
            return base.Channel.ListarSalaDeAulaPorConceitoAsync(conceito);
        }
        
        public DiretorSkinner.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorTurma(DiretorSkinner.Tranporte.TurmaDto turma) {
            return base.Channel.ListarSalaDeAulaPorTurma(turma);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorTurmaAsync(DiretorSkinner.Tranporte.TurmaDto turma) {
            return base.Channel.ListarSalaDeAulaPorTurmaAsync(turma);
        }
        
        public DiretorSkinner.Tranporte.SalaDeAulaDto[] ListarSalaDeAulaPorFiltros(DiretorSkinner.Tranporte.ConceitoDto conceito, DiretorSkinner.Tranporte.DisciplinaDto disciplina, DiretorSkinner.Tranporte.PessoaDto pessoa, DiretorSkinner.Tranporte.TurmaDto turma) {
            return base.Channel.ListarSalaDeAulaPorFiltros(conceito, disciplina, pessoa, turma);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.SalaDeAulaDto[]> ListarSalaDeAulaPorFiltrosAsync(DiretorSkinner.Tranporte.ConceitoDto conceito, DiretorSkinner.Tranporte.DisciplinaDto disciplina, DiretorSkinner.Tranporte.PessoaDto pessoa, DiretorSkinner.Tranporte.TurmaDto turma) {
            return base.Channel.ListarSalaDeAulaPorFiltrosAsync(conceito, disciplina, pessoa, turma);
        }
        
        public void SalvarSalaDeAula(DiretorSkinner.Tranporte.SalaDeAulaDto SalaDeAula) {
            base.Channel.SalvarSalaDeAula(SalaDeAula);
        }
        
        public System.Threading.Tasks.Task SalvarSalaDeAulaAsync(DiretorSkinner.Tranporte.SalaDeAulaDto SalaDeAula) {
            return base.Channel.SalvarSalaDeAulaAsync(SalaDeAula);
        }
        
        public void DeletarSalaDeAula(DiretorSkinner.Tranporte.SalaDeAulaDto SalaDeAula) {
            base.Channel.DeletarSalaDeAula(SalaDeAula);
        }
        
        public System.Threading.Tasks.Task DeletarSalaDeAulaAsync(DiretorSkinner.Tranporte.SalaDeAulaDto SalaDeAula) {
            return base.Channel.DeletarSalaDeAulaAsync(SalaDeAula);
        }
        
        public DiretorSkinner.Tranporte.TurmaDto[] ListarTurmas() {
            return base.Channel.ListarTurmas();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.TurmaDto[]> ListarTurmasAsync() {
            return base.Channel.ListarTurmasAsync();
        }
        
        public void SalvarTurma(DiretorSkinner.Tranporte.TurmaDto turma) {
            base.Channel.SalvarTurma(turma);
        }
        
        public System.Threading.Tasks.Task SalvarTurmaAsync(DiretorSkinner.Tranporte.TurmaDto turma) {
            return base.Channel.SalvarTurmaAsync(turma);
        }
        
        public void DeletarTurma(DiretorSkinner.Tranporte.TurmaDto turma) {
            base.Channel.DeletarTurma(turma);
        }
        
        public System.Threading.Tasks.Task DeletarTurmaAsync(DiretorSkinner.Tranporte.TurmaDto turma) {
            return base.Channel.DeletarTurmaAsync(turma);
        }
        
        public DiretorSkinner.Tranporte.TipoPessoaDto[] ListarTiposPessoa() {
            return base.Channel.ListarTiposPessoa();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.TipoPessoaDto[]> ListarTiposPessoaAsync() {
            return base.Channel.ListarTiposPessoaAsync();
        }
        
        public DiretorSkinner.Tranporte.TipoPessoaDto ListarTipoPessoa(int id) {
            return base.Channel.ListarTipoPessoa(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.TipoPessoaDto> ListarTipoPessoaAsync(int id) {
            return base.Channel.ListarTipoPessoaAsync(id);
        }
        
        public DiretorSkinner.Tranporte.TipoPessoaDto[] ListarTipoPessoaPorPessoa(DiretorSkinner.Tranporte.PessoaDto pessoa) {
            return base.Channel.ListarTipoPessoaPorPessoa(pessoa);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.TipoPessoaDto[]> ListarTipoPessoaPorPessoaAsync(DiretorSkinner.Tranporte.PessoaDto pessoa) {
            return base.Channel.ListarTipoPessoaPorPessoaAsync(pessoa);
        }
        
        public void SalvarTipoPessoa(DiretorSkinner.Tranporte.TipoPessoaDto tipoPessoa) {
            base.Channel.SalvarTipoPessoa(tipoPessoa);
        }
        
        public System.Threading.Tasks.Task SalvarTipoPessoaAsync(DiretorSkinner.Tranporte.TipoPessoaDto tipoPessoa) {
            return base.Channel.SalvarTipoPessoaAsync(tipoPessoa);
        }
        
        public void DeletarTipoPessoa(DiretorSkinner.Tranporte.TipoPessoaDto tipoPessoa) {
            base.Channel.DeletarTipoPessoa(tipoPessoa);
        }
        
        public System.Threading.Tasks.Task DeletarTipoPessoaAsync(DiretorSkinner.Tranporte.TipoPessoaDto tipoPessoa) {
            return base.Channel.DeletarTipoPessoaAsync(tipoPessoa);
        }
        
        public DiretorSkinner.Tranporte.TipoDisciplinaDto[] ListarTiposDisciplina() {
            return base.Channel.ListarTiposDisciplina();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.TipoDisciplinaDto[]> ListarTiposDisciplinaAsync() {
            return base.Channel.ListarTiposDisciplinaAsync();
        }
        
        public DiretorSkinner.Tranporte.TipoDisciplinaDto ListarTipoDisciplina(int id) {
            return base.Channel.ListarTipoDisciplina(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.TipoDisciplinaDto> ListarTipoDisciplinaAsync(int id) {
            return base.Channel.ListarTipoDisciplinaAsync(id);
        }
        
        public void SalvarTipoDisciplina(DiretorSkinner.Tranporte.TipoDisciplinaDto tipoDisciplina) {
            base.Channel.SalvarTipoDisciplina(tipoDisciplina);
        }
        
        public System.Threading.Tasks.Task SalvarTipoDisciplinaAsync(DiretorSkinner.Tranporte.TipoDisciplinaDto tipoDisciplina) {
            return base.Channel.SalvarTipoDisciplinaAsync(tipoDisciplina);
        }
        
        public void DeletarTipoDisciplina(DiretorSkinner.Tranporte.TipoDisciplinaDto tipoDisciplina) {
            base.Channel.DeletarTipoDisciplina(tipoDisciplina);
        }
        
        public System.Threading.Tasks.Task DeletarTipoDisciplinaAsync(DiretorSkinner.Tranporte.TipoDisciplinaDto tipoDisciplina) {
            return base.Channel.DeletarTipoDisciplinaAsync(tipoDisciplina);
        }
        
        public DiretorSkinner.Tranporte.DisciplinaDto[] ListarDisciplinas() {
            return base.Channel.ListarDisciplinas();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.DisciplinaDto[]> ListarDisciplinasAsync() {
            return base.Channel.ListarDisciplinasAsync();
        }
        
        public DiretorSkinner.Tranporte.DisciplinaDto[] ListarDisciplinaPorTipo(DiretorSkinner.Tranporte.TipoDisciplinaDto tipoDisciplina) {
            return base.Channel.ListarDisciplinaPorTipo(tipoDisciplina);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.DisciplinaDto[]> ListarDisciplinaPorTipoAsync(DiretorSkinner.Tranporte.TipoDisciplinaDto tipoDisciplina) {
            return base.Channel.ListarDisciplinaPorTipoAsync(tipoDisciplina);
        }
        
        public DiretorSkinner.Tranporte.DisciplinaDto ListarDisciplina(int id) {
            return base.Channel.ListarDisciplina(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.DisciplinaDto> ListarDisciplinaAsync(int id) {
            return base.Channel.ListarDisciplinaAsync(id);
        }
        
        public void SalvarDisciplina(DiretorSkinner.Tranporte.DisciplinaDto disciplina) {
            base.Channel.SalvarDisciplina(disciplina);
        }
        
        public System.Threading.Tasks.Task SalvarDisciplinaAsync(DiretorSkinner.Tranporte.DisciplinaDto disciplina) {
            return base.Channel.SalvarDisciplinaAsync(disciplina);
        }
        
        public void DeletarDisciplina(DiretorSkinner.Tranporte.DisciplinaDto disciplina) {
            base.Channel.DeletarDisciplina(disciplina);
        }
        
        public System.Threading.Tasks.Task DeletarDisciplinaAsync(DiretorSkinner.Tranporte.DisciplinaDto disciplina) {
            return base.Channel.DeletarDisciplinaAsync(disciplina);
        }
        
        public DiretorSkinner.Tranporte.ConceitoDto[] ListarConceitos() {
            return base.Channel.ListarConceitos();
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ConceitoDto[]> ListarConceitosAsync() {
            return base.Channel.ListarConceitosAsync();
        }
        
        public DiretorSkinner.Tranporte.ConceitoDto ListarConceito(int id) {
            return base.Channel.ListarConceito(id);
        }
        
        public System.Threading.Tasks.Task<DiretorSkinner.Tranporte.ConceitoDto> ListarConceitoAsync(int id) {
            return base.Channel.ListarConceitoAsync(id);
        }
        
        public void SalvarConceito(DiretorSkinner.Tranporte.ConceitoDto conceito) {
            base.Channel.SalvarConceito(conceito);
        }
        
        public System.Threading.Tasks.Task SalvarConceitoAsync(DiretorSkinner.Tranporte.ConceitoDto conceito) {
            return base.Channel.SalvarConceitoAsync(conceito);
        }
        
        public void DeletarConceito(DiretorSkinner.Tranporte.ConceitoDto conceito) {
            base.Channel.DeletarConceito(conceito);
        }
        
        public System.Threading.Tasks.Task DeletarConceitoAsync(DiretorSkinner.Tranporte.ConceitoDto conceito) {
            return base.Channel.DeletarConceitoAsync(conceito);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
    }
}
